/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CaseId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'scheduled' : IDL.Null,
  'reviewing' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Record({ 'comments' : IDL.Text, 'reason' : IDL.Text }),
  'accepted' : IDL.Null,
});
export const Case = IDL.Record({
  'status' : Status,
  'documents' : IDL.Vec(ExternalBlob),
  'hearingDate' : Time,
  'clientName' : IDL.Text,
  'caseNumber' : IDL.Text,
  'jlNo' : IDL.Text,
  'khationNo' : IDL.Text,
  'createdDate' : Time,
  'mutionNo' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptCase' : IDL.Func([CaseId, IDL.Vec(ExternalBlob), IDL.Text], [], []),
  'addCase' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
      [CaseId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'editCase' : IDL.Func(
      [CaseId, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getAllDocumentMetadata' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'documentId' : ExternalBlob, 'caseId' : CaseId }))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCase' : IDL.Func([CaseId], [IDL.Opt(Case)], ['query']),
  'getCaseDocuments' : IDL.Func([CaseId], [IDL.Vec(ExternalBlob)], ['query']),
  'getCasesByStatus' : IDL.Func([Status], [IDL.Vec(Case)], ['query']),
  'getCasesSortedByCaseNumber' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getCasesSortedByClientName' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getCasesSortedByHearingDate' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getDocumentsByCaseStatus' : IDL.Func(
      [Status],
      [IDL.Vec(ExternalBlob)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectCase' : IDL.Func([CaseId, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CaseId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'scheduled' : IDL.Null,
    'reviewing' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Record({ 'comments' : IDL.Text, 'reason' : IDL.Text }),
    'accepted' : IDL.Null,
  });
  const Case = IDL.Record({
    'status' : Status,
    'documents' : IDL.Vec(ExternalBlob),
    'hearingDate' : Time,
    'clientName' : IDL.Text,
    'caseNumber' : IDL.Text,
    'jlNo' : IDL.Text,
    'khationNo' : IDL.Text,
    'createdDate' : Time,
    'mutionNo' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptCase' : IDL.Func([CaseId, IDL.Vec(ExternalBlob), IDL.Text], [], []),
    'addCase' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
        [CaseId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'editCase' : IDL.Func(
        [CaseId, IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getAllDocumentMetadata' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({ 'documentId' : ExternalBlob, 'caseId' : CaseId })
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCase' : IDL.Func([CaseId], [IDL.Opt(Case)], ['query']),
    'getCaseDocuments' : IDL.Func([CaseId], [IDL.Vec(ExternalBlob)], ['query']),
    'getCasesByStatus' : IDL.Func([Status], [IDL.Vec(Case)], ['query']),
    'getCasesSortedByCaseNumber' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getCasesSortedByClientName' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getCasesSortedByHearingDate' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getDocumentsByCaseStatus' : IDL.Func(
        [Status],
        [IDL.Vec(ExternalBlob)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectCase' : IDL.Func([CaseId, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };